FROM python:3.6-alpine as base-dev

COPY setup.py requirements-dev.txt yggscr/
COPY src yggscr/src
COPY docs yggscr/docs
COPY conf yggscr/conf
COPY docker yggscr/docker

WORKDIR yggscr/
RUN pip install wheel && pip wheel . --wheel-dir=wheels


FROM python:3.6-alpine as uwsgi
COPY --from=base-dev yggscr/ /opt/yggscr
WORKDIR /opt/yggscr
RUN apk --update --no-cache add uwsgi uwsgi-python3 && \
    mkdir /run/ygg/ && chown -R uwsgi:uwsgi /run/ygg && \
    cp conf/ygg.ini src/yserver/
RUN pip install --no-index --find-links=/opt/yggscr/wheels -r requirements-dev.txt

ENV PYTHONPATH /opt/yggscr/src

WORKDIR src/yserver
ENTRYPOINT ["/opt/yggscr/docker/stage/conf-setup.sh"]
CMD [ "uwsgi", "--ini", "ygg.ini", "--pythonpath", "/usr/local/lib/python3.6/site-packages", "--pythonpath", "/opt/yggscr/src"]

EXPOSE 8333
VOLUME /run/ygg/
